### ISSUE TITLE
Schedule a hangouts/skype/viber chat to discuss the project goals

### ISSUE THREAD

**Issue by mharizanov** [mharizanov/node_pki#1]
@kOld @Quentinb Let's schedule a chat on the project, we can use hangouts/skype/viber.

My availability is here: [Doodle](https://doodle.com/poll/zbchrgtek3wfx2au)

I am located in Sofia (GMT+3)

**Comment by mharizanov** [comment]
Oh dear, I use Doodle for the first time to schedule a meeting. It looks confusing now that I look at it. Basically I  wanted to chat for roughly an hour sometime in the evenings or anytime the weekend.

**Comment by Quentinb** [comment]
Hi Martin, 

No problem,
Friday works for me, else Sunday.

Kind Regards
Quentin

**Comment by mharizanov** [comment]
How's this Friday, 8pm Sofia time for everyone?

**Comment by Quentinb** [comment]
looks good for me. (I'm GMT+2)

**Comment by kOld** [comment]
My timezone is GMT, but unfortunately Friday will be a very full day for me, anyway, you guys should talk, I can catch up later any developments. Next week I will have a bit more time to spend on this

**Comment by mharizanov** [comment]
Quentin, I'll open a google hangouts session at 8pm GMT+3, search for me mharizanov@gmail.com

**Comment by mharizanov** [comment]
https://hangouts.google.com/call/8H29zl0YxISv3NagdwzKAEEI

**Comment by mharizanov** [comment]
Lets continue the chat on Slack https://join.slack.com/t/node-pki/shared_invite/enQtNjU1NzgwMzg3MTIzLWFkZTkzNzVjNGQ5MTViMjY5YWQ2Nzg5N2FmNjA3MGFmY2E2YTk4ZGZhZDcwMDIzZDM3ZTZmNjU0ZTk1NWE2YTA
